### ISSUE TITLE
Colab error: kwargs   unexpected keyword argument: 'ocr_reader_name' (type=type_error

### ISSUE THREAD

**Issue by Tylersuard** [impira/docquery#21]
I just switch to GPU and do a "run all" and this is the error I get

**Comment by ankrgyl** [comment]
Oh wow, that was fast! We just merged this in. CC @amazingvince.

**Comment by ankrgyl** [comment]
@Tylersuard I just pushed a fix. Do you mind trying again?

**Comment by ankrgyl** [comment]
@Tylersuard checking in -- are you still encountering this error?

**Comment by Tylersuard** [comment]
@ankrgyl Nope!  It works now with the GPU.

**Comment by Tylersuard** [comment]
@ankrgyl however I find it has a hard time drawing from information located at different parts in a document.  For instance, I opened a PDF talking about animals, and I asked which animals were discussed.  Docquery was unable to answer.

**Comment by ankrgyl** [comment]
Good to hear about the GPU. Are you willing to share the file that you are trying out? Happy to take a look at it (preferably in a separate issue).

**Comment by ankrgyl** [comment]
Closing this out as the discussion has moved to https://github.com/impira/docquery/issues/24
