### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by izdi** [impira/docquery#26]
```
$ docquery scan "What is the invoice number?" https://templates.invoicehome.com/invoice-template-us-neat-750px.png
Illegal instruction: 4
```

Just go this running on Mac M1, is it supported? 

Any suggestions to resolve would be helpful 🙏

Warm regards

**Comment by ankrgyl** [comment]
Hi @izdi that looks like an issue related to Rosetta -- usually this occurs if one of your dependencies (e.g. `torch`) was installed with Rosetta, and it is trying to use a SIMD instruction that Rosetta can't emulate.

Could you share some more details about how you've installed `docquery` and whether or not you're using Rosetta? Are you running in a virtual environment or did you install it globally?

**Comment by izdi** [comment]
Hi @ankrgyl, thanks for the follow-up!

I installed `docquery` it with `pip` within `conda` env.

``` active environment : base
    active env location : /Users/izdi/opt/anaconda3
            shell level : 1
       user config file : /Users/izdi/.condarc
 populated config files : /Users/izdi/.condarc
          conda version : 4.13.0
    conda-build version : 3.20.5
         python version : 3.8.13.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/izdi/opt/anaconda3  (writable)
      conda av data dir : /Users/izdi/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/izdi/opt/anaconda3/pkgs
                          /Users/izdi/.conda/pkgs
       envs directories : /Users/izdi/opt/anaconda3/envs
                          /Users/izdi/.conda/envs
               platform : osx-64
             user-agent : conda/4.13.0 requests/2.28.0 CPython/3.8.13 Darwin/21.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
``` 

Currently, I'm on Monterey, but frankly I don't remember if I installed `torch` on Rosetta, I'll try `torch` reinstallation.

**Comment by ankrgyl** [comment]
I'm guessing it's this:

```
                          __archspec=1=x86_64
```

I'm not a conda expert, but that indicates that the conda environment is x86. If you run the `arch` command from the terminal you're in (with and without the conda env active) what do you get?

**Comment by izdi** [comment]
```
$ arch
arm64
```

I guess you're right! 

Should I just reinstall `conda` or environment?

**Comment by ankrgyl** [comment]
I'm not familiar enough with Conda to know 100%, but I do recall there being an explicit arm vs x86 option when you download and install it.

--
Ankur Goyal

CEO, Impira

Make Meaningful

Sent via Superhuman iOS ( ***@***.*** )

**Comment by izdi** [comment]
I reinstalled conda for arm64 and reinstalled everything, and it worked.

During `tokenizers` installation, I got this error: 
```
running build_ext
      running build_rust
      error: can't find Rust compiler
```

You might want to update the docs to include Rust requirements.

Thanks for the help!

**Comment by ankrgyl** [comment]
Thanks for the tip -- I suspect that also may be a conda-specific quirk (I believe it comes pre-compiled in other environments). We'll do some more digging and update the docs accordingly.

Were you able to install Rust and proceed forward?

**Comment by izdi** [comment]
@ankrgyl yes. Playing with it looks promising!

One question, tho', if you ask, "What is the description of all items?" it returns only the first one or the last one depending on the framing of the question. Why do you think that might happen?

```(base) izdi at ~
$ docquery scan "What is the description of all line items?" https://templates.invoicehome.com/invoice-template-us-neat-750px.png

image-classification is already registered. Overwriting pipeline for task image-classification...
2022-09-14 17:17:20,105 INFO: Loading https://templates.invoicehome.com/invoice-template-us-neat-750px.png
2022-09-14 17:17:20,105 INFO: Done loading files. Loading pipeline...2022-09-14 17:17:28,125 INFO: Ready to start evaluating!

https://templates.invoicehome.com/invoice-template-us-neat-750px.png What is the description of all line items?: Front and rear brake cables

(base) izdi at ~
$ docquery scan "What is the description of all items?" https://templates.invoicehome.com/invoice-template-us-neat-750px.png

image-classification is already registered. Overwriting pipeline for task image-classification...
2022-09-14 17:18:23,226 INFO: Loading https://templates.invoicehome.com/invoice-template-us-neat-750px.png
2022-09-14 17:18:23,226 INFO: Done loading files. Loading pipeline...
2022-09-14 17:18:30,372 INFO: Ready to start evaluating!

https://templates.invoicehome.com/invoice-template-us-neat-750px.png What is the description of all items?: Front and rear brake cables

(base) izdi at ~
$ docquery scan "What is the description of QTY 1 2 3?" https://templates.invoicehome.com/invoice-template-us-neat-750px.png

image-classification is already registered. Overwriting pipeline for task image-classification...
2022-09-14 17:18:56,499 INFO: Loading https://templates.invoicehome.com/invoice-template-us-neat-750px.png
2022-09-14 17:18:56,499 INFO: Done loading files. Loading pipeline...
2022-09-14 17:19:04,022 INFO: Ready to start evaluating!

https://templates.invoicehome.com/invoice-template-us-neat-750px.png What is the description of QTY 1 2 3?: Labor Shrs
```

**Comment by ankrgyl** [comment]
Hi @izdi let's move the discussion over here https://github.com/impira/docquery/discussions/33 so that we can keep this thread focused on the installation issues. I'll follow up there.

**Comment by ankrgyl** [comment]
Hi @izdi I'm going to close this out because it looks like we were able to solve your installation issue. Please let me know if you have any other questions.
