### ISSUE TITLE
pipeline on list based input

### ISSUE THREAD

**Issue by amazingvince** [impira/docquery#3]
pipeline([{"image": image, "question": question}]) input format fails. 

The pipeline treats the list as `image` and fails to extract question from dict on line 196 in pipeline.  
The error is "TypeError: list indices must be integers or slices, not str"

Example:
`p = pipeline.get_pipeline()`
`doc = document.load_document("example.pdf")`
`print(p([{**doc.context, 'question': "Who authored this paper?"}]))`

**Comment by ankrgyl** [comment]
As it stands, the pipeline can only accept one question as input (i.e. if `images` is a list, it assumes that it's a list of images that all correspond to the same question).
