### ISSUE TITLE
Doesn't work with PDF 

### ISSUE THREAD

**Issue by vanalize** [impira/docquery#36]
`docquery scan "What is the invoice number?" https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf`

Errors:

- FileNotFoundError: [Errno 2] No such file or directory: 'pdfinfo'

- pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?

**Comment by ankrgyl** [comment]
Hi Vanilize, do you have `poppler` installed on your system? The error seems to indicate that it's missing. I ran it on my machine and saw this output:

```
$ docquery scan "What is the invoice number?" https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf

image-classification is already registered. Overwriting pipeline for task image-classification...
2022-09-18 09:10:00,114 INFO: Loading https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf
2022-09-18 09:10:00,114 INFO: Done loading files. Loading pipeline...
2022-09-18 09:10:01,397 INFO: Ready to start evaluating!
https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf What is the invoice number?: INV-3337
```

**Comment by vanalize** [comment]
you were right! Thanks

**Comment by ankrgyl** [comment]
Thanks for following up -- please let me know if you have any other questions. We hope to address this confusing UX in #20 since for the PDF you linked, Poppler is technically unnecessary.
