### ISSUE TITLE
How to Uninstall this along with all Downloaded Files for pipeline?

### ISSUE THREAD

**Issue by ibehnam** [impira/docquery#43]
Just the title. Multiple files were downloaded upon first use. I wonder where they go and how the package and those files can be deleted in the future.

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/58621210/192163008-6ea7eaf3-3df3-447a-8779-8c4dd52523c4.png">

**Comment by ankrgyl** [comment]
Hi @ibehnam, the files you linked are from the https://github.com/huggingface/transformers library. They're usually cached in your home directory (`~/.cache/huggingface/`).

**Comment by ankrgyl** [comment]
I'm going to close this out, but please feel free to re-open if you have any other questions.
