### ISSUE TITLE
support document type

### ISSUE THREAD

**Issue by zhiwenyou103** [impira/docquery#48]
Hi! I want to ask whether the DocQuery supports .json file as document input?

**Comment by ankrgyl** [comment]
Oh interesting question. It currently does not directly, but I'm sure we could come up with a clever way to. Could you try generating a screenshot or PDF file from the JSON file and checking if it works?

Also, if you can share the JSON and question you'd like to ask, I can provide some tips.

**Comment by zhiwenyou103** [comment]
> 

Thank you for your reply. The .json file contains the context and question as keys. 
It shows like:
`[{'positive_ctxs': {'title': 'The Halting Problem P4',
   'text': 'As discussed in the textbook and in class, a { universal\ncomputational device} (or { computing machine}) is a device \nthat is capable of computing the\nsolution to any problem that can be computed, provided that the device\nis given enough storage and time for the computation to finish.  '},
  'questions': '\nQ. What is a universal computational device?',
  'answers': '\n\nA. A universal computational device is a device that is capable of computing the solution to any problem that can be computed, provided that the device is given enough storage and time for the computation to finish.'},
 {'positive_ctxs': {'title': 'The Halting Problem P5',
   'text': 'One might ask whether we can describe problems that we cannot answer (other \nthan philosophical ones, such as the meaning of life).'},
  'questions': '\nQ. What is the meaning of life?',
  'answers': '\n\nA. We cannot answer this question other than through philosophical means.'}]`

Any tips about implementation will be super helpful!

**Comment by ankrgyl** [comment]
Ah, and to clarify, would you like to run each question in the JSON file against the (plain text) context?

**Comment by zhiwenyou103** [comment]
> Ah, and to clarify, would you like to run each question in the JSON file against the (plain text) context?

Exactly. I would like to ask DocQuery to retrieve answer for each question based on each 'text' key.

**Comment by zhiwenyou103** [comment]
BTW, can DocQuery return the customized number of answers given ONE question? (e.g., for each question, the model can return several answers except for the most relevant one)

**Comment by ankrgyl** [comment]
Got it. I'm not sure you actually even need DocQuery to perform this task, since your text context is just plain text. For example, on Vanilla transformers, I was able to do this:

```
from transformers import pipeline

data = [{'positive_ctxs': {'title': 'The Halting Problem P4', 'text': 'As discussed in the textbook and in class, a { universal\ncomputational device} (or { computing machine}) is a device \nthat is capable of computing the\nsolution to any problem that can be computed, provided that the device\nis given enough storage and time for the computation to finish. '}, 'questions': '\nQ. What is a universal computational device?', 'answers': '\n\nA. A universal computational device is a device that is capable of computing the solution to any problem that can be computed, provided that the device is given enough storage and time for the computation to finish.'}, {'positive_ctxs': {'title': 'The Halting Problem P5', 'text': 'One might ask whether we can describe problems that we cannot answer (other \nthan philosophical ones, such as the meaning of life).'}, 'questions': '\nQ. What is the meaning of life?', 'answers': '\n\nA. We cannot answer this question other than through philosophical means.'}]

# top_k sets how many answers you want the pipeline to return (each with a score)
pipe = pipeline('question-answering', max_answer_len=128, top_k=3)
pipe(question=data[0]['questions'][0], context=data[0]['positive_ctxs']['text'])

# Returns something like this:
# [{'score': 0.47350358963012695, 'start': 20, 'end': 28, 'answer': 'textbook'},
#  {'score': 0.1505853682756424,
#   'start': 20,
#   'end': 41,
#   'answer': 'textbook and in class'},
#  {'score': 0.041666436940431595,
#   'start': 16,
#   'end': 28,
#   'answer': 'the textbook'}]
```

Does that help? Please let me know if I'm missing anything.

**Comment by zhiwenyou103** [comment]
> 

Thank you so much! I believe this would be helpful.
