### ISSUE TITLE
Donut dependencies

### ISSUE THREAD

**Issue by hsm207** [impira/docquery#49]
I installed docquery in a fresh python environment and followed the [readme ](https://github.com/impira/docquery#using-donut-) to run it using donut but ran into dependency issues. I had to install the following libraries to get it to work:

```
sentencepiece==0.1.97
protobuf==3.20.3
```
Just wanted to share this in case others run into the same problems.

**Comment by ankrgyl** [comment]
Thanks @hsm207. If you run `pip install docquery[donut]` it should pull those dependencies in. That said, we don't make that very clear in the README, and now that donut has been shipped within transformers, we should be simply pin an upgraded version of transformers and simplify the README.

**Comment by ankrgyl** [comment]
@hsm207 I just published [an update to the dependencies + README](https://github.com/impira/docquery/commit/a9c51272d0ecc766c2e0b2b11805b9ba66739ffe), as well as a new version of DocQuery (0.0.7) that simplifies things.

**Comment by hsm207** [comment]
@ankrgyl awesome! thanks for the update!

**Comment by AmineDjeghri** [comment]
@ankrgyl , `pip install docquery[donut]` doesn't seem to work. I get this error `no matches found: docquery[donut]`/
I followed @hsm207 workaround to get it work
