### ISSUE TITLE
How to output top 3/5 answers?

### ISSUE THREAD

**Issue by zhiwenyou103** [impira/docquery#50]
Hello! May I ask how to adjust the number of output answers? I would like to get more than ONE answer. Thank you!

**Comment by ankrgyl** [comment]
Hi! Yes, you can simply provide `top_k` as an argument to the pipeline. For example:

```
pipe(question="What is the title?", **doc.context, top_k=3)
```

**Comment by zhiwenyou103** [comment]
> Hi! Yes, you can simply provide `top_k` as an argument to the pipeline. For example:
> 
> ```
> pipe(question="What is the title?", **doc.context, top_k=3)
> ```

Thanks a lot!!
