### ISSUE TITLE
LayoutLM Squad Training

### ISSUE THREAD

**Issue by logan-markewich** [impira/docquery#53]
what approach did you use for fine-tuning layoutlm on squad?

Since there is no visual element to squad, did you input blank boxes or null boxes? Or maybe generate synthetic documents?

**Comment by ankrgyl** [comment]
We generated synthetic documents!

**Comment by logan-markewich** [comment]
Very cool! 

Are you able to share your approach? If not I totally understand

**Comment by ankrgyl** [comment]
Unfortunately cannot share the documents at this time, but the general approach is quite straightforward: just convert the plain text context into a media document from which you can extract bounding boxes alongside the text.

**Comment by logan-markewich** [comment]
Makes sense, thanks for sharing 👍

**Comment by munish0838** [comment]
Hi @logan-markewich, I am also trying to fine tune layoutlm for vqa tasks. As mentioned above, were you able to fine tune LayoutLM on SQUAD or other similar datasets like CUAD? Can you please share the process for fine tuning on question answering?

**Comment by logan-markewich** [comment]
For squad (and by extension, cuad) you just need to generate text images. I used https://github.com/microsoft/genalog

There are also many examples online for training docvqa. Here's one: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/DocVQA/Fine_tuning_LayoutLMv2ForQuestionAnswering_on_DocVQA.ipynb

**Comment by munish0838** [comment]
> 

Thank you for sharing these 
The problem I am facing is with training (impira/layoutlm-document-qa) model from huggingface
LayoutLmv1 and LayoutLMv2 have different architectures and tokenizers
Since this model is based on LayoutLMv1, I am unable to use scripts and techniques meant for LayoutLmv2

I am looking for model already pre trained on DocVQA, (and Squad if possible) to further train it on CUAD dataset

**Comment by logan-markewich** [comment]
Right! But training something other than layoutlmv2 is usually just a matter of swapping the tokenizer and model, and then adjusting the inputs (I.e layoutlmv1 does not use the image as a direct input). It might take some work, but not a lot.

Many docvqa models on huggingface to pick from: https://huggingface.co/models?sort=downloads&search=Docvqa

**Comment by munish0838** [comment]
Thank you @logan-markewich 
This is really helpful
